# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VoiceXML-Client
version:      1.01
version_from: lib/VoiceXML/Client.pm
installdirs:  site
requires:
    Hash::Util:                    0.05
    HTTP::Cookies:                 1.39
    LWP::UserAgent:                2
    XML::Mini:                     1.36

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
